let pets = [
  {
    name: "rock",
    price: 5,
    color: "gray",
    animal: false,
    url: "https://assets.stickpng.com/thumbs/580b585b2edbce24c47b26f0.png",
  },
  {
    name: "dog",
    price: 25,
    color: "brown",
    animal: true,
    url: "https://www.pasadenastarnews.com/wp-content/uploads/2021/05/PAS-L-COL-PHS-0526-01.jpeg?w=467",
  },
  {
    name: "fish",
    price: 2,
    color: "orange",
    animal: true,
    url: "https://squeaksandnibbles.com/wp-content/uploads/2019/07/Goldfish-names-SN-long.jpg",
  },
  {
    name: "mouse",
    price: 15,
    color: "brown",
    animal: true,
    url: "https://media.istockphoto.com/id/492697068/photo/cut-out-field-mouse.jpg?s=612x612&w=0&k=20&c=KX9dJmu-HF6dYbwNqb2mhSJmpyVHDB_7V7yGfbCPNhA=",
  },
  {
    name: "gaming mouse",
    price: 45,
    color: "rbg",
    animal: false,
    url: "https://resource.logitechg.com/w_572,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/gaming/en/non-braid/hyjal-g502-hero/g502-hero-gallery-1-nb.png?v=1",
  },
  {
    name: "lizard",
    price: 16,
    color: "green",
    animal: true,
    url: "https://i0.wp.com/post.healthline.com/wp-content/uploads/2021/06/lizard-iguana-1296x728-header.jpg?w=1155&h=1528",
  },
  {
    name: "ketchup packet",
    price: 1,
    color: "red",
    animal: false,
    url: "https://i5.walmartimages.com/asr/00d4c0b5-b853-4f02-bebe-da2b57d927db.503a11bce48689491fcef71ae7c0c7ba.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
  },
  {
    name: "crab",
    price: 42,
    color: "red",
    animal: true,
    url: "https://media.fisheries.noaa.gov/styles/original/s3/2021-03/640x427-Crab_Atlantic_Deep_Sea_Red_NB_W.jpg?itok=5ccYxI_1",
  },
  {
    name: "monkey",
    price: 892,
    color: "gray",
    animal: true,
    url: "https://media.npr.org/assets/img/2017/09/12/macaca_nigra_self-portrait-3e0070aa19a7fe36e802253048411a38f14a79f8-s800-c85.webp",
  },
  {
    name: "banana slug",
    price: 92,
    color: "orange",
    animal: true,
    url: "https://upload.wikimedia.org/wikipedia/commons/4/46/Two_Banana_Slugs.jpg",
  },
  {
    name: "starfish",
    price: 68,
    color: "red",
    animal: true,
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Starfish.jpg/1024px-Starfish.jpg",
  },
  {
    name: "beetle",
    price: 23,
    color: "brown",
    animal: true,
    url: "https://animals.sandiegozoo.org/sites/default/files/2016-10/beetle_frog.jpg",
  },
  {
    name: "beatles",
    price: 12899,
    color: "gray",
    animal: true,
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/The_Fabs.JPG/220px-The_Fabs.JPG",
  },
  {
    name: "tiger",
    price: 4212,
    color: "orange",
    animal: true,
    url: "https://files.worldwildlife.org/wwfcmsprod/images/Tiger_Walking_Madhya_Pradesh_India/story_full_width/9ghsu6o0ow_Medium_WW246778.jpg",
  },
  {
    name: "jello",
    price: 3,
    color: "red",
    animal: false,
    url: "https://www.happy-mothering.com/wp-content/uploads/2017/01/finger-jello-horizontal.webp",
  },
  {
    name: "kangaroo",
    price: 42,
    color: "gray",
    animal: true,
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Kangaroo_Australia_01_11_2008_-_retouch.JPG/1024px-Kangaroo_Australia_01_11_2008_-_retouch.JPG",
  },
  {
    name: "tree",
    price: 2131,
    color: "brown",
    animal: false,
    url: "https://www.santacruzsentinel.com/wp-content/uploads/migration/2016/201610/NEWS_161029890_AR_0_SGIDUXAPZQFX.jpg?w=535",
  },
  {
    name: "spider",
    price: 23,
    color: "brown",
    animal: true,
    url: "https://th-thumbnailer.cdn-si-edu.com/UBWiQEswjK9RY0jafz7kcjHag0s=/1000x750/filters:no_upscale():focal(1162x775:1163x776)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/a7/a0/a7a0b2fa-de95-4198-a453-8c8cfd86121a/female_frontal.jpg",
  },
  {
    name: "spiderman",
    price: 423,
    color: "red",
    animal: true,
    url: "https://insidethemagic.net/wp-content/uploads/2021/12/Spider-Man2-800x400.png",
  },
  {
    name: "spotted lanturn fly",
    price: 0.02,
    color: "red",
    animal: true,
    url: "https://www.canr.msu.edu/contentAsset/image/7c92121b-0935-4df5-bd2b-6a7510d5b8c7/fileAsset/filter/Resize,Jpeg/resize_w/750/jpeg_q/80",
  },
  {
    name: "pizza",
    price: 3,
    color: "orange",
    animal: false,
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
  },
  {
    name: "hot dog",
    price: 4,
    color: "red",
    animal: true,
    url: "https://www.quiktrip.com/app/uploads/2021/10/MicrosoftTeams-image-5.jpg",
  },
];

export { pets };
